# Generated by Django 3.2 on 2021-04-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
